version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "bkircher"
    ignore:
      - dependency-name: "black"
    groups:
      minor-and-patch-updates:
        update-types:
          - "minor"
          - "patch"
